apiVersion: v1
kind: ServiceAccount
metadata:
  name: djs-account
  namespace: "default"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: djs-role-cluster
rules:
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [koutsikos.dev]
    resources: [dynamicjobschedulers]
    verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: djs-role
  namespace: "default"
rules:
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [koutsikos.dev]
    resources: [dynamicjobschedulers]
    verbs: [list, watch, patch]
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [create]
  - apiGroups: [""]
    resources: [pods]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: djs-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: djs-role-cluster
subjects:
  - kind: ServiceAccount
    name: djs-account
    namespace: "default"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "default"
  name: djs-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: djs-role
subjects:
  - kind: ServiceAccount
    name: djs-account
