apiVersion: apps/v1
kind: Deployment
metadata:
  name: djs-mocker
  labels:
    app: djs-mocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djs-mocker
  template:
    metadata:
      labels:
        app: djs-mocker
    spec:
      containers:
        - name: djs-mocker
          image: djs-mocker:1.0
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: djs-mocker-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
      app: djs-mocker
